#!/usr/local/bin/node
(function () {
    "use strict";
    require('./booklog')
        .setParam({
            userId: 'xxxx',
            basePath: '/xxxx/xxx/xxxxxx'
        })
        .genBookLogFolders();
}());


