#!/usr/local/bin/node
(function (args) {
    "use strict";
    require('./booklog')
        .setting({
            args: process.argv,
            userId: 'xxxx',
            basePath: '/xxxx/xxx/xxxxxx'
        })
        .genBookLogFolders();
}());


